---
apiVersion: v1
kind: Deployment
metadata:
  name: "devopsgirls-deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "devopsgirls"
  template:
    metadata:
      labels:
        app: "devopsgirls"
    spec:
      containers:
        - image: "mydockerusername/devopsgirls:latest"
          name: nginx
          ports:
            - containerPort: 80
 

---
apiVersion: v1
kind: Service
metadata:
  name: "devopsgirls-service"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: "devopsgirls"
